definitions:
  auth.Code:
    properties:
      code:
        type: string
      email:
        type: string
      password:
        type: string
    type: object
  auth.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  auth.RegisterRequest:
    properties:
      email:
        type: string
      full_name:
        type: string
      password:
        type: string
      user_type:
        type: string
      username:
        type: string
    type: object
  auth.RegisterResponse:
    properties:
      created_at:
        type: string
      email:
        type: string
      full_name:
        type: string
      id:
        type: string
      user_type:
        type: string
      username:
        type: string
    type: object
  auth.ResetRequest:
    properties:
      email:
        type: string
    type: object
  auth.ResetResponse:
    properties:
      message:
        type: string
    type: object
  auth.Status:
    properties:
      successful:
        type: boolean
    type: object
  auth.Token:
    properties:
      refresh_token:
        type: string
    type: object
  auth.Tokens:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  description: Authorazation API
  title: Authorazation
  version: "1.0"
paths:
  /auth/forgot-password:
    post:
      description: Sends reset code to user's email
      parameters:
      - description: Email
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/auth.ResetRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.ResetResponse'
        "400":
          description: Invalid data
          schema:
            type: string
        "500":
          description: Server error while processing request
          schema:
            type: string
      summary: Sends reset code
      tags:
      - auth
  /auth/login:
    post:
      description: Logs user in
      parameters:
      - description: User credentials
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/auth.LoginRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.Tokens'
        "400":
          description: Invalid data
          schema:
            type: string
        "500":
          description: Server error while processing request
          schema:
            type: string
      summary: Logs user in
      tags:
      - auth
  /auth/logout:
    post:
      description: Logs user out
      parameters:
      - description: Refresh token
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/auth.Token'
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Invalid data
          schema:
            type: string
        "500":
          description: Server error while processing request
          schema:
            type: string
      summary: Logs user out
      tags:
      - auth
  /auth/refresh-token:
    post:
      description: Refreshes refresh token
      parameters:
      - description: Refresh token
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/auth.Token'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.Tokens'
        "400":
          description: Invalid data
          schema:
            type: string
        "500":
          description: Server error while processing request
          schema:
            type: string
      summary: Refreshes refresh token
      tags:
      - auth
  /auth/register:
    post:
      description: Inserts new user into database
      parameters:
      - description: New user data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/auth.RegisterRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.RegisterResponse'
        "400":
          description: Invalid data
          schema:
            type: string
        "500":
          description: Server error while processing request
          schema:
            type: string
      summary: Registers user
      tags:
      - auth
  /auth/reset-password:
    post:
      description: Resets password based on reset code
      parameters:
      - description: Details
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/auth.Code'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.Status'
        "400":
          description: Invalid data
          schema:
            type: string
        "500":
          description: Server error while processing request
          schema:
            type: string
      summary: Resets password
      tags:
      - auth
swagger: "2.0"
